name: ESLint CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install

      - name: Install ESLint
        run: yarn add eslint

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx